[project]
name = "google_maps_pb_viewer"
version = "0.0.1"
description = "Google Maps pb viewer"
readme = "README.md"
license = {text = "MIT"}
requires-python = ">=3.10"

authors = [
  {name = "Etienne HODE", email = "hode.etienne@gmail.com"}
]
maintainers = [
  {name = "Etienne HODE", email = "hode.etienne@gmail.com"}
]

dependencies = []

keywords = ["pb", "protobuf", "google maps"]

[project.scripts]
decode_pb = "google_maps_pb_viewer.__main__:main"

[project.urls]
Homepage = "https://github.com/etienne-hd/google_maps_pb_viewer"
Repository = "https://github.com/etienne-hd/google_maps_pb_viewer"
Changelog = "https://github.com/etienne-hd/google_maps_pb_viewer/blob/main/CHANGELOG.md"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"