[project]
name = "google_maps_pb_viewer"
version = "0.0.1"
description = "Google Maps pb viewer"
readme = "README.md"
authors = [
    { name = "etienne-hd", email = "hode.etienne@gmail.com" }
]
requires-python = ">=3.10"
dependencies = []

[project.scripts]
decode_pb = "google_maps_pb_viewer.__main__:main"

[build-system]
requires = ["uv_build>=0.11.7,<0.12.0"]
build-backend = "uv_build"

[tool.uv.workspace]
members = [
    "test/google_maps_pb_viewer",
]

